### ISSUE TITLE
crafters cannot craft at the same time

### ISSUE THREAD

**Issue by krakaen** [McJty/EFab#8] opened 2018-05-23 18:54 UTC
I am trying to craft the printed circuits in Continuum.

In the 2 images below, you can see that the screen shows that at least one of them is idle at all time. 1 is always Idle if I try to craft the 4 different printed "STUFF" at the same time.

- They have separate inventory, 
- They are all named 
- When 3 are working, the 3 of them work.

they need : Gearbox, RF, RF upgrade and Digital upgrade

![image](https://user-images.githubusercontent.com/8230693/40444775-43128800-5e98-11e8-8691-132bff10793c.png)
![image](https://user-images.githubusercontent.com/8230693/40444783-479beb28-5e98-11e8-91db-7e87c48aad78.png)

**Comment by McJty** [comment] 2018-05-24 13:30
I'm a bit confused with this. What exactly goes wrong? Is this an actual crafting bug or is the screen wrong?

**Comment by krakaen** [comment] 2018-05-24 15:18
When I try to craft the 4 printed things *At the same time* in Continuum. one of them will not craft until one of the other 3 finishes crafting. the screen is only there to show that it idle.

**Comment by McJty** [comment] 2018-05-27 14:12
I cannot reproduce this. No clue what is going on...

**Comment by zeryl** [comment] 2018-06-14 18:04
Not sure if this helps, but I have several autocrafters (also in continuum).  I added something like 15 power upgrades just in case.  But as you see, it's an error on the screen.  It's due to missing the power upgrade.  

https://i.imgur.com/Euo26MP.png

The example of the silicon processor, it flashes "The power upgrade is needed", even though there are numerous of them in the efab crafting grid.  Additionally, it's only flashing, and DOES produce them, occasionally.

**Comment by McJty** [comment] 2018-06-14 18:07
How many grids do you have on your multiblock?

**Comment by zeryl** [comment] 2018-06-14 18:08
@McJty  I have two, and all of those upgrades are in one.  Do they need to be split? Does it need a grid PER auto-craft item?

Edit: Looks like it, need 1 crafting grid per autocraft item, if you want them to run concurrently.

**Comment by McJty** [comment] 2018-06-20 10:00
This will be fixed next version. It will no longer be required to have multiple grids and if multiple grids are present it will pick the grid with most upgrades in it (as opposed to the random grid you get now which may not have the required upgrade)

**Closed as completed by McJty** 2018-06-20 10:00 UTC
